obj-y += uart/

obj-$(CONFIG_MS_ISP_FLASH) += flash_isp/
obj-$(CONFIG_MS_PARTITION) += partition/
obj-$(CONFIG_MS_SDMMC) += sdmmc/
obj-$(CONFIG_MS_GPIO) += gpio/
#obj-$(CONFIG_MS_AESDMA) += aesdma/

obj-$(CONFIG_SSTAR_DISP) += disp/
obj-$(CONFIG_SSTAR_PNL) += panel/
obj-$(CONFIG_SSTAR_JPD) += jpd/
obj-$(CONFIG_SSTAR_MSPI) += spi/
#obj-$(CONFIG_SSTAR_SAR) += sar/
#obj-$(CONFIG_SSTAR_PWM) += pwm/
obj-$(CONFIG_SYS_I2C_MSTAR) += i2c/
obj-$(CONFIG_MS_SRCFG) += isp/